version: '3.8'

services:
  medconnect_postgres:
    image: postgres:15
    container_name: medconnect-postgres
    environment:
      POSTGRES_DB: medconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: medconnect-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: medconnect-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "kafka:29092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  autenticacao:
    build:
      context: .
      dockerfile: servicos/autenticacao/Dockerfile
    container_name: medconnect-autenticacao
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      medconnect_postgres:
        condition: service_healthy

  servico-agendamento:
    build:
      context: .
      dockerfile: servicos/servico-agendamento/Dockerfile
    container_name: medconnect-agendamento
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      medconnect_postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  servico-notificacao:
    build:
      context: .
      dockerfile: servicos/servico-notificacao/Dockerfile
    container_name: medconnect-notificacao
    ports:
      - "8082:8082"
    env_file:
      - .env
    depends_on:
      medconnect_postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy

  servico-historico:
    build:
      context: .
      dockerfile: servicos/servico-historico/Dockerfile
    container_name: medconnect-historico
    ports:
      - "8083:8083"
    env_file:
      - .env
    depends_on:
      medconnect_postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
