spring:
  application:
    name: servico-agendamento   

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/medconnect}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: medconnect
      auto-offset-reset: earliest
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:mySuperSecretKeyThatIsLongEnoughForHS256AlgorithmAndMore}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    org.hibernate: DEBUG
    org.hibernate.tool.schema: DEBUG
    com.adjt.medconnect.servicoagendamento.common: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
